//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.21 at 07:18:03 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.demo.com/Ekyc_Auth/1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package JaxB_Classes;
